# Generated by Django 5.2.17 on 2026-09-08 18:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0014_orgassistantconfig_pricing_and_source_sharing'),
        ('reports', '0020_sharelink_embed_appearance'),
        ('studios', '0011_studiorepo_publish_requested_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('after_build', 'After every successful build'), ('schedule', 'On a schedule')], default='after_build', max_length=16)),
                ('freq', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16)),
                ('send_hour', models.PositiveSmallIntegerField(default=8)),
                ('send_minute', models.PositiveSmallIntegerField(default=0)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('month_day', models.PositiveSmallIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('recipient_roles', models.JSONField(blank=True, default=list)),
                ('cooldown_hours', models.PositiveIntegerField(default=24)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='orgs.organization')),
                ('recipient_groups', models.ManyToManyField(blank=True, related_name='alert_rules', to='orgs.permissiongroup')),
                ('recipients', models.ManyToManyField(blank=True, related_name='alert_rule_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='reports.report')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='AlertRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('skipped_budget', 'Skipped: budget'), ('skipped_cooldown', 'Skipped: cooldown')], default='ok', max_length=24)),
                ('decision', models.CharField(blank=True, choices=[('alert', 'Alert'), ('quiet', 'Quiet')], default='', max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=11)),
                ('delivered_to', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
