# Generated by Django 5.2.17 on 2026-10-09 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrun',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=11, null=True),
        ),
    ]
