# Generated by Django 5.2.17 on 2026-08-12 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='+', to='orgs.permissiongroup'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='orgs.organization'),
        ),
    ]
