# Generated by Django 5.2.17 on 2026-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation_groups_invitation_invited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_operator_flag',
            field=models.BooleanField(db_column='is_operator', default=False, verbose_name='operator console access'),
        ),
    ]
