# Generated by Django 5.2.17 on 2026-08-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_auth_epoch_recoverycode_totpdevice_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
