# Generated by Django 5.2.17 on 2026-08-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
