# Generated by Django 5.2.17 on 2026-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_erased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dormancy_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
