# Generated by Django 5.2.17 on 2026-08-12 00:51

import apps.core.crypto
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0002_studiorepo_sync_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$', 'Source names are 1-64 chars: letters, digits, underscore, hyphen (reports reference this name in report.yaml).')])),
                ('type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('vertica', 'Vertica'), ('clickhouse', 'ClickHouse'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite file'), ('file', 'Data file (CSV/Excel)'), ('onedrive', 'OneDrive / SharePoint')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials', apps.core.crypto.EncryptedJSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='studios.studio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('studio', 'name'), name='uniq_source_per_studio')],
            },
        ),
    ]
