# Generated by Django 5.2.17 on 2026-08-12 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
        ('orgs', '0003_orgssoconfig_enforce_sso'),
        ('studios', '0002_studiorepo_sync_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='studios.studio'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('vertica', 'Vertica'), ('clickhouse', 'ClickHouse'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite file'), ('file', 'Data file (CSV/Excel)'), ('image', 'Image (logo, background, asset)'), ('onedrive', 'OneDrive / SharePoint')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uniq_source_per_org'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('org__isnull', True), ('studio__isnull', False)), models.Q(('org__isnull', False), ('studio__isnull', True)), _connector='OR'), name='source_has_exactly_one_scope'),
        ),
    ]
