# Generated by Django 5.2.17 on 2026-09-05 13:35

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_datasource_org_alter_datasource_studio_and_more'),
        ('studios', '0008_studio_repo_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$', 'Source names are 1-64 chars: letters, digits, underscore, hyphen (reports reference this name in report.yaml).')])),
                ('type', models.CharField(max_length=64)),
                ('config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('source_file', models.CharField(max_length=300)),
                ('present', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_sources', to='studios.studio')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('studio', 'name'), name='uniq_repo_source_per_studio')],
            },
        ),
    ]
