# Generated by Django 5.2.17 on 2026-09-05 14:00

from django.db import migrations, models


def flag_pre_sync_rows(apps, schema_editor):
    """Rows that exist before declarations were ever synced must not read as
    "not in the repository" until a sync has actually looked. Flag them, and
    ask every repository for one sync so the flag clears itself."""
    DataSource = apps.get_model("datasources", "DataSource")
    StudioRepo = apps.get_model("studios", "StudioRepo")
    repos = StudioRepo.objects.all()
    studio_ids = list(repos.values_list("studio_id", flat=True))
    org_ids = list(repos.values_list("studio__org_id", flat=True))
    DataSource.objects.filter(studio_id__in=studio_ids).update(awaiting_first_sync=True)
    DataSource.objects.filter(org_id__in=org_ids).update(awaiting_first_sync=True)
    repos.update(sync_requested=True)


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_repodatasource'),
        ('studios', '0008_studio_repo_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='awaiting_first_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_check_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_check_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(flag_pre_sync_rows, migrations.RunPython.noop),
    ]
