# Generated by Django 5.2.17 on 2026-09-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_datasource_check_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='repodatasource',
            name='file_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='repodatasource',
            name='shipped_path',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
