# Generated by Django 5.2.17 on 2026-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0005_repodatasource_file_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('vertica', 'Vertica'), ('clickhouse', 'ClickHouse'), ('sqlserver', 'SQL Server'), ('redshift', 'Redshift'), ('trino', 'Trino'), ('databricks', 'Databricks'), ('snowflake', 'Snowflake'), ('bigquery', 'BigQuery'), ('google_sheets', 'Google Sheets'), ('sqlite', 'SQLite file'), ('duckdb', 'DuckDB file'), ('file', 'Data file (CSV/Excel)'), ('image', 'Image (logo, background, asset)'), ('onedrive', 'OneDrive / SharePoint')], max_length=20),
        ),
    ]
