# Generated by Django 5.2.17 on 2026-08-12 00:22

import apps.core.crypto
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$|^[a-z0-9]$', 'Slugs are 1-64 chars of lowercase letters, digits and hyphens.')])),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StudioMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('admin', 'Admin')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studios.studio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudioRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(help_text='HTTPS clone URL of the reports repository.')),
                ('branch', models.CharField(default='main', max_length=100)),
                ('path', models.CharField(default='reports', help_text='Directory inside the repository that holds the report folders.', max_length=200)),
                ('auth_method', models.CharField(choices=[('https_token', 'HTTPS + token'), ('none', 'Public / no auth')], default='https_token', max_length=16)),
                ('token', apps.core.crypto.EncryptedTextField(blank=True, default='')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=5, help_text='0 disables polling (manual / webhook sync only).')),
                ('auto_run_changed', models.BooleanField(default=False, help_text='Rebuild reports whose files changed in a pulled commit.')),
                ('webhook_secret', apps.core.crypto.EncryptedTextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_sha', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='studios.studio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studio',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='uniq_studio_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='studiomembership',
            constraint=models.UniqueConstraint(fields=('user', 'studio'), name='uniq_studio_membership'),
        ),
    ]
