# Generated by Django 5.2.17 on 2026-08-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiorepo',
            name='sync_requested',
            field=models.BooleanField(default=False),
        ),
    ]
