# Generated by Django 5.2.17 on 2026-08-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studiorepo_sync_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='pool',
            field=models.CharField(choices=[('small', 'Small'), ('standard', 'Standard'), ('large', 'Large')], default='standard', max_length=32),
        ),
    ]
