# Generated by Django 5.2.17 on 2026-08-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_studiowatchlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudioWatchLevel',
        ),
    ]
