# Generated by Django 5.2.17 on 2026-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_delete_studiowatchlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='studiomembership',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
