# Generated by Django 5.2.17 on 2026-08-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_studio_theme_studiomembership_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='repo_theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
