# Generated by Django 5.2.17 on 2026-09-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0008_studio_repo_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudioWebhook',
        ),
    ]
