# Generated by Django 5.2.17 on 2026-09-05 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_delete_studiowebhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studiorepo',
            name='pending_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='publish_mode',
            field=models.CharField(choices=[('auto', 'Publish every push'), ('manual', 'Review, then publish')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='publish_rebuild_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='publish_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='publish_requested_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='remote_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='remote_sha',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='studiorepo',
            name='sync_reason',
            field=models.CharField(choices=[('schedule', 'schedule'), ('manual', 'manual'), ('webhook', 'webhook')], default='schedule', max_length=16),
        ),
        migrations.CreateModel(
            name='RepoPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_sha', models.CharField(blank=True, max_length=64)),
                ('to_sha', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual'), ('webhook', 'webhook'), ('initial', 'initial')], max_length=8)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('error', 'error')], default='ok', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('published_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishes', to='studios.studio')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['studio', 'published_at'], name='repopublish_studio_at')],
            },
        ),
    ]
