# Generated by Django 5.2.17 on 2026-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0010_publish_mode_and_repopublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiorepo',
            name='publish_requested_to',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
