# Generated by Django 5.2.17 on 2026-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0011_studiorepo_publish_requested_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='default_analysis_audience',
            field=models.CharField(choices=[('studio', 'Studio audience'), ('private', 'Private')], db_default='studio', default='studio', max_length=16),
        ),
        migrations.AddField(
            model_name='studio',
            name='default_report_audience',
            field=models.CharField(choices=[('studio', 'Studio audience'), ('private', 'Private')], db_default='studio', default='studio', max_length=16),
        ),
    ]
