# Generated by Django 5.2.17 on 2026-08-14 22:55

import apps.core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(default='BI Portal', max_length=100)),
                ('public_base_url', models.URLField(blank=True, default='', help_text='Absolute URL of this portal, used for invitation links, SSO redirect URIs and report back-links. Blank = use PORTAL_BASE_URL from the environment.')),
                ('email_host', models.CharField(blank=True, default='', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(blank=True, default='', max_length=255)),
                ('email_host_password', apps.core.crypto.EncryptedTextField(blank=True, default='')),
                ('email_from', models.EmailField(blank=True, default='', max_length=254)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'instance configuration',
                'verbose_name_plural': 'instance configuration',
            },
        ),
    ]
