# Generated by Django 5.2.17 on 2026-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instanceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='max_upload_mb',
            field=models.PositiveIntegerField(default=512, help_text="Largest data-source file a tenant may upload, in MB. 0 = no limit. Your reverse proxy must allow at least this much too — nginx's client_max_body_size defaults to 1 MB."),
        ),
    ]
