# Generated by Django 5.2.17 on 2026-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instanceconfig_max_upload_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='instance_name',
            field=models.CharField(default='trellum', max_length=100),
        ),
    ]
