# Generated by Django 5.2.17 on 2026-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog_impersonator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ran_at', models.DateTimeField()),
                ('ok', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'ops state',
                'verbose_name_plural': 'ops state',
            },
        ),
    ]
