# Generated by Django 5.2.17 on 2026-08-26 19:09, hand-edited per docs/MIGRATIONS.md:
# the four new indexes go on AuditLog, which "only ever grows" (see the
# impersonator field's comment in apps/core/models.py) -- a plain AddIndex
# would hold a lock across the whole build. AddIndexConcurrently needs
# atomic = False, so the column adds ride along in the same non-atomic
# migration; each is a metadata-only ADD COLUMN on Postgres 11+ (a fixed
# default, no null=True needed) and none of them depend on the indexes.
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False  # CONCURRENTLY cannot run inside a transaction

    dependencies = [
        ('core', '0009_rename_cache_table'),
        ('orgs', '0007_orgquota_max_storage_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='category',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(default='success', max_length=8),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        AddIndexConcurrently(
            model_name='auditlog',
            index=models.Index(fields=['org', 'category', '-created_at'], name='core_auditl_org_id_cd60af_idx'),
        ),
        AddIndexConcurrently(
            model_name='auditlog',
            index=models.Index(fields=['org', 'actor', '-created_at'], name='core_auditl_org_id_044ce4_idx'),
        ),
        AddIndexConcurrently(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='core_auditl_target__29612b_idx'),
        ),
        AddIndexConcurrently(
            model_name='auditlog',
            index=models.Index(condition=models.Q(('outcome', 'success'), _negated=True), fields=['org', '-created_at'], name='idx_audit_non_success'),
        ),
    ]
