# Generated by Django 5.2.17 on 2026-08-26 21:51

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_audit_backfill_category_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='lockout_account_threshold',
            field=models.PositiveIntegerField(default=apps.core.models._default_lockout_account_threshold, help_text='Failed attempts against one account before it cools off. 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='lockout_cooloff_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Cooloff after crossing a threshold. Doubles on repeat lockouts of the same key within 24h, capped at 240.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='lockout_ip_threshold',
            field=models.PositiveIntegerField(default=30, help_text='Failed attempts from one client address before it cools off (higher: shared NAT). 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='lockout_window_minutes',
            field=models.PositiveIntegerField(default=apps.core.models._default_lockout_window_minutes, help_text='Rolling window the two thresholds above are counted over.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='require_mfa_operators',
            field=models.BooleanField(default=False, help_text='Require instance operators (is_superuser / is_operator) to have MFA enrolled.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='session_absolute_hours',
            field=models.PositiveIntegerField(default=720, help_text="Hard cap on a session's age from login, regardless of activity. 0 = disabled."),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='session_expire_at_browser_close',
            field=models.BooleanField(default=False, help_text='Sessions become non-persistent cookies unless remember-me is ticked.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='session_idle_minutes',
            field=models.PositiveIntegerField(default=720, help_text='Sign out after this many minutes of inactivity. 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='session_remember_me_days',
            field=models.PositiveIntegerField(default=30, help_text='Idle window granted when remember-me is ticked. The absolute cap still applies.'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='session_remember_me_enabled',
            field=models.BooleanField(default=False, help_text='Show a "Keep me signed in" checkbox on the login form. (Not yet built.)'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='sessions_invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
