# Generated by Django 5.2.17 on 2026-10-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_email_api_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLogEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=16)),
                ('service', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=255)),
                ('process', models.PositiveIntegerField()),
                ('logger', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('exception', models.TextField(blank=True, default='')),
                ('context', models.JSONField(default=dict)),
                ('worker_id', models.CharField(blank=True, default='', max_length=100)),
                ('run_id', models.CharField(blank=True, default='', max_length=36)),
                ('report_slug', models.CharField(blank=True, default='', max_length=200)),
                ('request_id', models.CharField(blank=True, default='', max_length=200)),
                ('trigger', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['timestamp'], name='server_log_time_idx'), models.Index(fields=['run_id', 'id'], name='server_log_run_idx'), models.Index(fields=['worker_id', 'id'], name='server_log_worker_idx')],
            },
        ),
    ]
