# Generated by Django 5.2.17 on 2026-08-12 00:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_beat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_concurrent', models.IntegerField(default=3)),
                ('running_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('starting', 'Starting'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('stopped', 'Stopped'), ('timeout', 'Timed out'), ('oom_killed', 'OOM killed')], default='queued', max_length=16)),
                ('cache_mode', models.CharField(choices=[('normal', 'Normal'), ('fresh', 'Fresh (no cache)'), ('force', 'Force cache'), ('debug', 'Debug'), ('debug-fresh', 'Debug + fresh')], default='normal', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('git', 'Git push'), ('catchup', 'Boot catch-up')], default='manual', max_length=16)),
                ('stop_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout_tail', models.TextField(blank=True, default='')),
                ('stderr_tail', models.TextField(blank=True, default='')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, default='', max_length=100)),
                ('log_dir', models.CharField(blank=True, default='', max_length=400)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reports.report')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='studios.studio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-priority', 'created_at'], name='runner_run_status_f204d0_idx'), models.Index(fields=['studio', 'slug', '-created_at'], name='runner_run_studio__245a27_idx')],
            },
        ),
    ]
