# Generated by Django 5.2.17 on 2026-08-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='peak_memory_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
