# Generated by Django 5.2.17 on 2026-08-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_run_memory_limit_mb_run_peak_memory_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerheartbeat',
            name='memory_budget_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerheartbeat',
            name='reserved_memory_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerheartbeat',
            name='role',
            field=models.CharField(choices=[('all', 'Coordinator + runner'), ('coordinator', 'Coordinator'), ('runner', 'Runner')], default='all', max_length=16),
        ),
    ]
