# Generated by Django 5.2.17 on 2026-08-14 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_memory_mb'),
        ('runner', '0003_workerheartbeat_memory_budget_mb_and_more'),
        ('studios', '0003_studio_pool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='pool',
            field=models.CharField(default='standard', max_length=32),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'pool', 'created_at'], name='runner_run_status_fc00fa_idx'),
        ),
    ]
