# Generated by Django 5.2.17 on 2026-08-15 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_memory_mb'),
        ('runner', '0004_run_pool_run_runner_run_status_fc00fa_idx'),
        ('studios', '0003_studio_pool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['report', '-created_at'], name='run_report_created_idx'),
        ),
    ]
