# Generated by Django 5.2.17 on 2026-09-05 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmusage',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=11),
        ),
    ]
