# Generated by Django 5.2.17 on 2026-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_llmusage_cost_usd_six_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsession',
            name='in_flight_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
