# Generated by Django 5.2.17 on 2026-09-08 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_llmusage_user_survives_erasure'),
        ('orgs', '0019_orgassistantconfig_actions_enabled'),
        ('studios', '0011_studiorepo_publish_requested_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=300)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('secret_fields', models.JSONField(blank=True, default=list)),
                ('required_role', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired'), ('executed', 'executed'), ('failed', 'failed')], default='proposed', max_length=16)),
                ('result', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orgs.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='assistant.assistantsession')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='studios.studio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
