# Generated by Django 5.2.17 on 2026-09-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('assistant', '0005_proposedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsession',
            name='alert_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to='alerts.alertrun'),
        ),
    ]
