#!/usr/bin/env bash
#
# One command from a clean checkout to a rendered report in a browser.
#
# This exists because the artifact has to *be* the product. Anyone can
# read what Trellum does; almost nobody will assemble it from four manual
# steps to find out. Everything below runs with the normal product features.
#
#   ./scripts/demo.sh          bring it up and seed it
#   ./scripts/demo.sh --down   throw it all away again
#
# Not for production. It generates throwaway secrets and a known password,
# and says so on the way past. The real install path is in the docs.
#
# Running a SECOND demo alongside this one (e.g. to validate a change
# without disturbing a demo already in use)? Set both of these so the two
# never share a compose project, port, env file or image tag:
#   TRELLUM_DEMO_PROJECT=trellum-demo-2 TRELLUM_PORT=8051 ./scripts/demo.sh
set -euo pipefail

cd "$(dirname "$0")/.."

ORG_SLUG="demo"
ORG_NAME="Demo"
STUDIO_SLUG="demo"
EMAIL="demo@trellum.local"
PASSWORD="demo-Str0ng-pw"
PORT="${TRELLUM_PORT:-8050}"
PROJECT="${TRELLUM_DEMO_PROJECT:-trellum-demo}"
# The default project keeps the original ".env.demo" filename for anyone
# already relying on it; a custom project name gets its own env file so two
# instances never read (or clobber) each other's secrets.
if [ "$PROJECT" = "trellum-demo" ]; then
  ENV_FILE=".env.demo"
else
  ENV_FILE=".env.demo.${PROJECT}"
fi

say()  { printf '\n\033[1;36m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m !  %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR:\033[0m %s\n\n' "$*" >&2; exit 1; }

compose() { docker compose -p "$PROJECT" -f docker-compose.yml -f docker-compose.demo.yml "$@"; }

# ── teardown ────────────────────────────────────────────────────────────────
if [ "${1:-}" = "--down" ]; then
  say "Removing the demo (containers and volumes)"
  compose down -v --remove-orphans
  echo "Gone. $ENV_FILE is left alone; delete it by hand if you want."
  exit 0
fi

# ── preflight ───────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/get-docker/"
docker version --format '{{.Server.Version}}' >/dev/null 2>&1 \
  || die "Docker is installed but the daemon is not running. Start Docker Desktop and try again."

# ── secrets ─────────────────────────────────────────────────────────────────
# The single biggest reason "docker compose up" was never really one command:
# .env.example ships three blanks a newcomer has no way to fill in. Generate
# them. They are throwaway by construction and never leave this machine.
if [ ! -f "$ENV_FILE" ]; then
  say "Generating throwaway secrets into $ENV_FILE"
  gen() { docker run --rm python:3.12-slim python -c "$1" | tr -d '\r\n'; }
  SESSION_SECRET="$(gen 'import secrets;print(secrets.token_urlsafe(50))')"
  ENCRYPTION_KEY="$(gen 'from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())' 2>/dev/null || true)"
  if [ -z "$ENCRYPTION_KEY" ]; then
    ENCRYPTION_KEY="$(gen 'import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())')"
  fi
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/demo.sh. Throwaway values for a local demo -- never
# reuse any of this for an install that holds real data.
SESSION_SECRET_KEY=${SESSION_SECRET}
SECRET_ENCRYPTION_KEY=${ENCRYPTION_KEY}
POSTGRES_PASSWORD=$(gen 'import secrets;print(secrets.token_urlsafe(24))')
PORTAL_BASE_URL=http://localhost:${PORT}
ALLOWED_HOSTS=localhost,127.0.0.1
WORKER_MAX_CONCURRENT=2
EOF
  # Only needed when running alongside another instance from the same
  # checkout -- the default project keeps the shared trellum:dev tags.
  if [ "$PROJECT" != "trellum-demo" ]; then
    {
      echo "TRELLUM_IMAGE=${PROJECT}:dev"
      echo "TRELLUM_RUNNER_IMAGE=${PROJECT}-runner:dev"
    } >> "$ENV_FILE"
  fi
else
  say "Reusing the existing $ENV_FILE"
fi
export COMPOSE_ENV_FILES="$ENV_FILE"
# Read directly by docker-compose.demo.yml's env_file paths (see the comment
# there) -- COMPOSE_ENV_FILES alone does not repoint those.
export TRELLUM_DEMO_ENV_FILE="$ENV_FILE"

# ── the docker group id ─────────────────────────────────────────────────────
# The worker spawns a sandbox container per build, so it needs the socket, and
# compose refuses to start without DOCKER_GID. The documented way to find it
# (`getent group docker`) is Linux-only: on Docker Desktop there is no docker
# group on the host at all, because the socket lives in a VM.
#
# So ask Docker instead of the host. This is correct everywhere -- it reports
# the gid of the socket exactly as a container will see it, which is the
# number that actually matters. Exported rather than written to .env.demo: it
# is a property of this machine, and a copied env file would carry a wrong one.
#
# MSYS_NO_PATHCONV stops Git Bash rewriting /var/run/... into a Windows path
# before Docker ever sees it.
say "Asking Docker what group owns its socket"
DOCKER_GID="$(MSYS_NO_PATHCONV=1 docker run --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  alpine stat -c %g /var/run/docker.sock 2>/dev/null | tr -d '\r\n')"
if ! printf '%s' "${DOCKER_GID:-}" | grep -qE '^[0-9]+$'; then
  # Last resort for a host with no way to run that probe.
  DOCKER_GID="$(getent group docker 2>/dev/null | cut -d: -f3 || true)"
fi
[ -n "${DOCKER_GID:-}" ] || die "Could not determine the docker socket group id. Set DOCKER_GID and re-run."
export DOCKER_GID
echo "   DOCKER_GID=$DOCKER_GID"

# ── bring it up ─────────────────────────────────────────────────────────────
say "Building and starting Postgres, the web process and a worker"
echo "   (first run pulls images and builds -- several minutes is normal)"
# sandbox-image (the runner target) is what actually builds reports, so it
# must be rebuilt alongside web/worker. Otherwise a framework change lands in
# the portal image but report builds keep running a previously cached runner
# image, and every report using a new feature fails to build against stale code.
compose build db web worker sandbox-image

say "Waiting for the health checks the compose file already declares"
compose up -d --wait db migrate web worker ||
  die "The stack never became healthy. Logs:  docker compose -p $PROJECT logs web"

# ── seed ────────────────────────────────────────────────────────────────────
# Idempotent: re-running the script must not fail on an existing org.
if compose exec -T web python manage.py shell -c "
from apps.orgs.models import Organization
import sys; sys.exit(0 if Organization.objects.filter(slug='${ORG_SLUG}').exists() else 1)
" >/dev/null 2>&1; then
  say "The demo organization already exists -- skipping bootstrap"
else
  say "Creating the organization and an admin"
  compose exec -T web python manage.py bootstrap \
    --email "$EMAIL" --password "$PASSWORD" \
    --org-name "$ORG_NAME" --org-slug "$ORG_SLUG"
fi

# `bootstrap` creates the organization and its first admin, but not a studio --
# in normal use a studio is made in the UI, pointed at a git repository. The
# demo has no repository, so make one here and import into it. Same two steps
# the e2e job in CI takes.
say "Creating the demo studio"
compose exec -T web python manage.py shell -c "
from apps.orgs.models import Organization
from apps.studios.models import Studio
org = Organization.objects.get(slug='${ORG_SLUG}')
s, created = Studio.objects.get_or_create(
    org=org, slug='${STUDIO_SLUG}', defaults={'name': 'Demo'})
s.ensure_dirs()
print(('created' if created else 'already there') + ':', s.slug)
"

say "Generating the demo warehouse and importing the example reports"
# The fixtures are fabricated by the framework's own generator; nothing here
# is committed data. This is the same demo project a framework user gets from
# `python -m trellum.demo`.
#
# The demo project is NOT in the image -- .dockerignore excludes trellum/demo/
# on purpose, because a ~16 MB fixture database has no business in a
# customer's portal. That is the right call for the product and simply means
# the seed has to come from the checkout, so mount it.
#
# cygpath: Docker on Windows needs a Windows-style source path, and Git Bash
# would otherwise hand it a /c/... one. MSYS_NO_PATHCONV stops it rewriting
# the container-side path too.
HOST_DEMO="$(pwd)/trellum/demo"
if command -v cygpath >/dev/null 2>&1; then
  HOST_DEMO="$(cygpath -w "$HOST_DEMO")"
fi
seed() { MSYS_NO_PATHCONV=1 compose run --rm -v "${HOST_DEMO}:/seed" -T web "$@"; }

seed python /seed/tools/make_fixtures.py --small
seed python manage.py import_project "${ORG_SLUG}/${STUDIO_SLUG}" /seed

say "Queueing a build for every imported report"
echo "   (the worker runs each in a sandboxed subprocess, exactly as in production)"
compose exec -T web python manage.py shell -c "
from apps.reports.models import Report
from apps.runner.services import enqueue
reports = list(Report.objects.filter(
    studio__slug='${STUDIO_SLUG}', studio__org__slug='${ORG_SLUG}'))
if not reports:
    print('No reports found after import -- open the studio and press Build.')
for r in reports:
    enqueue(r, trigger='manual')
    print('queued:', r.slug)
" || warn "Could not queue builds. The import succeeded -- press Build in the studio."

echo
echo "   Builds run in the background; reports appear as they finish."
echo "   A slow first build is normal -- the runner image is built on demand."

# ── done ────────────────────────────────────────────────────────────────────
cat <<EOF

$(printf '\033[1;32m')Trellum is running.$(printf '\033[0m')

    http://localhost:${PORT}

    email     ${EMAIL}
    password  ${PASSWORD}

This demo uses the same product features as a self-hosted installation.

    logs      docker compose -p $PROJECT logs -f web worker
    stop      docker compose -p $PROJECT stop
    destroy   $(if [ "$PROJECT" = "trellum-demo" ]; then echo "./scripts/demo.sh --down"; else echo "TRELLUM_DEMO_PROJECT=$PROJECT ./scripts/demo.sh --down"; fi)

EOF
