<#
    One command from a clean checkout to a rendered report in a browser.

    The Windows twin of scripts/demo.sh -- same steps, same names, same
    throwaway secrets. Keep the two in step; a demo path that works on one
    platform and rots on the other is worse than not having it, because
    nobody finds out until a stranger tries it.

        .\scripts\demo.ps1          bring it up and seed it
        .\scripts\demo.ps1 -Down    throw it all away again

    Not for production: it generates throwaway secrets and a known password.

    Running a SECOND demo alongside this one (e.g. to validate a change
    without disturbing a demo already in use)? Set both of these so the two
    never share a compose project, port, env file or image tag:
        $env:TRELLUM_DEMO_PROJECT = 'trellum-demo-2'; $env:TRELLUM_PORT = '8051'
        .\scripts\demo.ps1
#>
[CmdletBinding()]
param([switch]$Down)

$ErrorActionPreference = 'Stop'
Set-Location (Join-Path $PSScriptRoot '..')

$OrgSlug    = 'demo'
$OrgName    = 'Demo'
$StudioSlug = 'demo'
$Email      = 'demo@trellum.local'
$Password   = 'demo-Str0ng-pw'
$Port       = if ($env:TRELLUM_PORT) { $env:TRELLUM_PORT } else { '8050' }
$Project    = if ($env:TRELLUM_DEMO_PROJECT) { $env:TRELLUM_DEMO_PROJECT } else { 'trellum-demo' }
# The default project keeps the original ".env.demo" filename for anyone
# already relying on it; a custom project name gets its own env file so two
# instances never read (or clobber) each other's secrets.
$EnvFile    = if ($Project -eq 'trellum-demo') { '.env.demo' } else { ".env.demo.$Project" }

function Say  ($m) { Write-Host "`n==> $m" -ForegroundColor Cyan }
function Warn ($m) { Write-Host " !  $m" -ForegroundColor Yellow }
function Die  ($m) { Write-Host "`nERROR: $m`n" -ForegroundColor Red; exit 1 }
function Compose { docker compose -p $Project -f docker-compose.yml -f docker-compose.demo.yml @args }

# ── teardown ────────────────────────────────────────────────────────────────
if ($Down) {
    if (-not (Test-Path $EnvFile -PathType Leaf)) {
        Die "Demo env file $EnvFile was not found. Start the demo first, or restore that file."
    }
    $env:COMPOSE_ENV_FILES = $EnvFile
    $env:TRELLUM_DEMO_ENV_FILE = $EnvFile
    # Teardown only needs Compose to resolve worker's group_add; it does not
    # need to probe Docker for the host's socket group.
    if (-not $env:DOCKER_GID) { $env:DOCKER_GID = '0' }
    Say 'Removing the demo (containers and volumes)'
    Compose down -v --remove-orphans
    if ($LASTEXITCODE -ne 0) { Die "Could not remove the demo project $Project." }
    Write-Host "Gone. $EnvFile is left alone; delete it by hand if you want."
    exit 0
}

# ── preflight ───────────────────────────────────────────────────────────────
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Die 'Docker is not installed. See https://docs.docker.com/get-docker/'
}
docker version --format '{{.Server.Version}}' *> $null
if ($LASTEXITCODE -ne 0) {
    Die 'Docker is installed but the daemon is not running. Start Docker Desktop and try again.'
}

# ── secrets ─────────────────────────────────────────────────────────────────
# The single biggest reason "docker compose up" was never really one command:
# .env.example ships three blanks a newcomer has no way to fill in.
if (-not (Test-Path $EnvFile)) {
    Say "Generating throwaway secrets into $EnvFile"
    function New-Secret([int]$Bytes) {
        $buf = New-Object byte[] $Bytes
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
        [Convert]::ToBase64String($buf).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    }
    # Fernet wants exactly 32 bytes, url-safe base64, padding INCLUDED.
    $fernetBuf = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($fernetBuf)
    $fernet = [Convert]::ToBase64String($fernetBuf).Replace('+', '-').Replace('/', '_')

    $lines = @(
      '# Generated by scripts/demo.ps1. Throwaway values for a local demo --'
      '# never reuse any of this for an install that holds real data.'
      "SESSION_SECRET_KEY=$(New-Secret 50)"
      "SECRET_ENCRYPTION_KEY=$fernet"
      "POSTGRES_PASSWORD=$(New-Secret 24)"
      "PORTAL_BASE_URL=http://localhost:$Port"
      'ALLOWED_HOSTS=localhost,127.0.0.1'
      'WORKER_MAX_CONCURRENT=2'
      'TRELLUM_SSO_DOMAIN_VERIFICATION=false'
    )
    # Only needed when running alongside another instance from the same
    # checkout -- the default project keeps the shared trellum:dev tags.
    if ($Project -ne 'trellum-demo') {
        $lines += "TRELLUM_IMAGE=${Project}:dev"
        $lines += "TRELLUM_RUNNER_IMAGE=${Project}-runner:dev"
    }
    $lines | Out-File -FilePath $EnvFile -Encoding utf8
} else {
    Say "Reusing the existing $EnvFile"
}
$env:COMPOSE_ENV_FILES = $EnvFile
# Read directly by docker-compose.demo.yml's env_file paths (see the comment
# there) -- COMPOSE_ENV_FILES alone does not repoint those.
$env:TRELLUM_DEMO_ENV_FILE = $EnvFile

# ── the docker group id ─────────────────────────────────────────────────────
# The worker spawns a sandbox container per build, so it needs the socket, and
# compose refuses to start without DOCKER_GID. The documented way to find it
# (`getent group docker`) is Linux-only -- on Docker Desktop there is no docker
# group on the host at all, because the socket lives in a VM. So ask Docker:
# this reports the gid exactly as a container will see it, which is the number
# that matters. Environment rather than .env.demo -- it is a property of this
# machine, and a copied env file would carry a wrong one.
Say 'Asking Docker what group owns its socket'
$gid = (docker run --rm -v /var/run/docker.sock:/var/run/docker.sock alpine stat -c %g /var/run/docker.sock 2>$null | Out-String).Trim()
if ($gid -notmatch '^\d+$') {
    Die 'Could not determine the docker socket group id. Set $env:DOCKER_GID and re-run.'
}
$env:DOCKER_GID = $gid
Write-Host "   DOCKER_GID=$gid"

# ── bring it up ─────────────────────────────────────────────────────────────
Say 'Building and starting Postgres, the web process and a worker'
Write-Host '   (first run pulls images and builds -- several minutes is normal)'
# sandbox-image (the runner target) is what actually builds reports, so it
# must be rebuilt alongside web/worker. Otherwise a framework change lands in
# the portal image but report builds keep running a previously cached runner
# image, and every report using a new feature fails to build against stale code.
Compose build db web worker sandbox-image
if ($LASTEXITCODE -ne 0) { Die 'The images did not build.' }

Say 'Waiting for the health checks the compose file already declares'
Compose up -d --wait db migrate web worker
if ($LASTEXITCODE -ne 0) {
    Die "The stack never became healthy. Logs:  docker compose -p $Project logs web"
}

# ── seed ────────────────────────────────────────────────────────────────────
# Idempotent: re-running must not fail on an existing org.
$exists = @"
from apps.orgs.models import Organization
import sys; sys.exit(0 if Organization.objects.filter(slug='$OrgSlug').exists() else 1)
"@
Compose exec -T web python manage.py shell -c $exists *> $null
if ($LASTEXITCODE -eq 0) {
    Say 'The demo organization already exists -- skipping bootstrap'
} else {
    Say 'Creating the organization and an admin'
    Compose exec -T web python manage.py bootstrap --email $Email --password $Password --org-name $OrgName --org-slug $OrgSlug
    if ($LASTEXITCODE -ne 0) { Die 'bootstrap failed.' }
}

# `bootstrap` creates the organization and its first admin, but not a studio --
# in normal use a studio is made in the UI, pointed at a git repository. The
# demo has no repository, so make one here. Same step the e2e job in CI takes.
Say 'Creating the demo studio'
$mkStudio = @"
from apps.orgs.models import Organization
from apps.studios.models import Studio
org = Organization.objects.get(slug='$OrgSlug')
s, created = Studio.objects.get_or_create(
    org=org, slug='$StudioSlug', defaults={'name': 'Demo'})
s.ensure_dirs()
print(('created' if created else 'already there') + ':', s.slug)
"@
Compose exec -T web python manage.py shell -c $mkStudio
if ($LASTEXITCODE -ne 0) { Die 'Could not create the demo studio.' }

Say 'Generating the demo warehouse and importing the example reports'
# Fabricated by the framework's own generator; nothing here is committed data.
#
# The demo project is NOT in the image -- .dockerignore excludes trellum/demo/
# on purpose, because a ~16 MB fixture database has no business in a
# customer's portal. So the seed comes from the checkout instead.
$hostDemo = (Resolve-Path 'trellum/demo').Path
Compose run --rm -v "${hostDemo}:/seed" -T web python /seed/tools/make_fixtures.py --small
if ($LASTEXITCODE -ne 0) { Die 'Generating the demo fixtures failed.' }
Compose run --rm -v "${hostDemo}:/seed" -T web python manage.py import_project "$OrgSlug/$StudioSlug" /seed
if ($LASTEXITCODE -ne 0) { Die 'import_project failed.' }

Say 'Queueing a build for every imported report'
Write-Host '   (the worker runs each in a sandboxed subprocess, exactly as in production)'
$queue = @"
from apps.reports.models import Report
from apps.runner.services import enqueue
reports = list(Report.objects.filter(
    studio__slug='$StudioSlug', studio__org__slug='$OrgSlug'))
if not reports:
    print('No reports found after import -- open the studio and press Build.')
for r in reports:
    enqueue(r, trigger='manual')
    print('queued:', r.slug)
"@
Compose exec -T web python manage.py shell -c $queue
if ($LASTEXITCODE -ne 0) {
    Warn 'Could not queue builds. The import succeeded -- press Build in the studio.'
}

Write-Host ''
Write-Host '   Builds run in the background; reports appear as they finish.'
Write-Host '   A slow first build is normal -- the runner image is built on demand.'

# ── done ────────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host 'Trellum is running.' -ForegroundColor Green
Write-Host ''
Write-Host "    http://localhost:$Port"
Write-Host ''
Write-Host "    email     $Email"
Write-Host "    password  $Password"
Write-Host ''
Write-Host 'This demo uses the same product features as a self-hosted installation.'
Write-Host ''
Write-Host "    logs      docker compose -p $Project logs -f web worker"
Write-Host "    stop      docker compose -p $Project stop"
if ($Project -eq 'trellum-demo') {
    Write-Host '    destroy   .\scripts\demo.ps1 -Down'
} else {
    Write-Host "    destroy   `$env:TRELLUM_DEMO_PROJECT = '$Project'; .\scripts\demo.ps1 -Down"
}
Write-Host ''
