# Generated by Django 5.2.17 on 2026-08-12 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='Uncategorized', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=100)),
                ('schedule_timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('disabled', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('present_in_scan', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='studios.studio')),
            ],
            options={
                'ordering': ['priority', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('studio', 'slug'), name='uniq_report_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='reportfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'report'), name='uniq_favorite'),
        ),
    ]
