# Generated by Django 5.2.17 on 2026-08-16 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_memory_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16)),
                ('send_hour', models.PositiveSmallIntegerField(default=8)),
                ('send_minute', models.PositiveSmallIntegerField(default=0)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('month_day', models.PositiveSmallIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('attach_pdf', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='email_schedule_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'user'), name='uniq_alert_subscription')],
            },
        ),
    ]
