# Generated by Django 5.2.17 on 2026-08-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_emailschedule_alertsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('currently_breaching', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rule_states', to='reports.report')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'rule_name'), name='uniq_alert_rule_state')],
            },
        ),
    ]
