# Generated by Django 5.2.17 on 2026-08-17 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alertrulestate'),
        ('runner', '0006_run_container_id_workerheartbeat_sandbox_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsubscription',
            name='mode',
            field=models.CharField(choices=[('alerts_on', 'Alerts on (force, incl. thresholds)'), ('muted', 'Muted (suppress despite studio level)')], default='alerts_on', max_length=16),
        ),
        migrations.CreateModel(
            name='BrokenReportPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='runner.run')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.report')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='runner.run')),
            ],
        ),
    ]
