# Generated by Django 5.2.17 on 2026-08-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alertsubscription_mode_brokenreportpending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertSubscription',
        ),
    ]
