# Generated by Django 5.2.17 on 2026-08-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_orgquota_max_storage_mb'),
        ('reports', '0006_delete_alertsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, related_name='email_schedules', to='orgs.permissiongroup'),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='recipient_roles',
            field=models.JSONField(blank=True, default=list, help_text='Subset of ["admins", "developers", "everyone"], expanded at send time.'),
        ),
    ]
