# Generated by Django 5.2.17 on 2026-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_orgsharepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsharepolicy',
            name='max_expiry_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgsharepolicy',
            name='require_password',
            field=models.BooleanField(default=False),
        ),
    ]
