# Generated by Django 5.2.17 on 2026-08-20 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_orgsharepolicy_max_expiry_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportViewDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_daily', to='reports.report')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'date'), name='uniq_view_daily')],
            },
        ),
        migrations.CreateModel(
            name='ReportViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='reports.report')),
                ('share_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.sharelink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'created_at'], name='idx_view_event_report_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('report', 'user', 'bucket'), name='uniq_view_event_user_bucket'), models.UniqueConstraint(condition=models.Q(('share_link__isnull', False)), fields=('report', 'share_link', 'bucket'), name='uniq_view_event_share_bucket')],
            },
        ),
    ]
