# Generated by Django 5.2.17 on 2026-08-26 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reportviewdaily_reportviewevent'),
        ('studios', '0006_delete_studiowatchlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=300)),
                ('format', models.CharField(default='number', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('agg', models.CharField(blank=True, default='', max_length=32)),
                ('column', models.CharField(blank=True, default='', max_length=200)),
                ('numerator', models.CharField(blank=True, default='', max_length=200)),
                ('denominator', models.CharField(blank=True, default='', max_length=200)),
                ('sql', models.TextField(blank=True, default='')),
                ('dimensions', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('definition_hash', models.CharField(blank=True, default='', max_length=64)),
                ('present_in_scan', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_definitions', to='studios.studio')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('studio', 'name'), name='uniq_metric_per_studio')],
            },
        ),
    ]
