# Generated by Django 5.2.17 on 2026-08-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_last_built_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
