# Generated by Django 5.2.17 on 2026-09-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_report_data_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.IntegerField(default=99),
        ),
    ]
