# Generated by Django 5.2.17 on 2026-09-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_report_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='memory_mb',
        ),
    ]
