# Generated by Django 5.2.17 on 2026-09-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_remove_report_memory_mb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertRuleState',
        ),
    ]
