# Generated by Django 5.2.17 on 2026-09-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_delete_alertrulestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsharepolicy',
            name='embed_links_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='embed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='embed_origins',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
