# Generated by Django 5.2.17 on 2026-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_sharelink_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='embed_hide_filters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='embed_theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
