# Generated by Django 5.2.17 on 2026-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_report_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='audience',
            field=models.CharField(choices=[('studio', 'Studio audience'), ('private', 'Private')], db_default='studio', default='studio', max_length=16),
        ),
    ]
