# Generated by Django 5.2.17 on 2026-08-12 00:22

import apps.core.crypto
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$|^[a-z0-9]$', 'Slugs are 1-64 chars of lowercase letters, digits and hyphens.')])),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgBuddyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI')], default='anthropic', max_length=16)),
                ('api_key', apps.core.crypto.EncryptedTextField(blank=True, default='')),
                ('model', models.CharField(blank=True, max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='Optional OpenAI-compatible gateway base URL.')),
                ('monthly_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('per_user_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_config', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('org_role', models.CharField(blank=True, choices=[('', 'No org-level role'), ('admin', 'Org admin')], default='', max_length=16)),
                ('default_studio_role', models.CharField(blank=True, choices=[('', 'No default'), ('viewer', 'Viewer'), ('developer', 'Developer'), ('admin', 'Admin')], default='', help_text='Applied to all current and future studios in the organization.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgSSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('entra_tenant_id', models.CharField(blank=True, max_length=64)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('client_secret', apps.core.crypto.EncryptedTextField(blank=True, default='')),
                ('email_domains', models.JSONField(blank=True, default=list, help_text='Login emails at these domains are routed to Entra (e.g. ["demo.example"]).')),
                ('auto_provision', models.BooleanField(default=False, help_text='Create portal accounts on first successful Entra login.')),
                ('default_org_role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=16)),
                ('entra_group_map', models.JSONField(blank=True, default=dict, help_text='Entra group object-id -> permission group id; synced on every login.')),
                ('allow_password_login', models.BooleanField(default=True, help_text="If off, users whose email matches this org's domains must use SSO.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='orgs.organization')),
                ('default_groups', models.ManyToManyField(blank=True, help_text='Permission groups attached to auto-provisioned users.', related_name='+', to='orgs.permissiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroupGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('admin', 'Admin')], max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='orgs.permissiongroup')),
            ],
        ),
    ]
