# Generated by Django 5.2.17 on 2026-08-12 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroupgrant',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_grants', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='permissiongroupmembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.permissiongroup'),
        ),
        migrations.AddField(
            model_name='permissiongroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orgmembership',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='uniq_org_membership'),
        ),
        migrations.AddConstraint(
            model_name='permissiongroup',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uniq_group_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='permissiongroupgrant',
            constraint=models.UniqueConstraint(fields=('group', 'studio'), name='uniq_grant_per_studio'),
        ),
        migrations.AddConstraint(
            model_name='permissiongroupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='uniq_group_membership'),
        ),
    ]
