# Generated by Django 5.2.17 on 2026-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgssoconfig',
            name='enforce_sso',
            field=models.BooleanField(default=False, help_text='Require SSO for every member of this organization, regardless of email domain — password login is refused (instance operators are exempt to prevent lockout).'),
        ),
    ]
