# Generated by Django 5.2.17 on 2026-08-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_orgssoconfig_enforce_sso'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_runs', models.PositiveIntegerField(default=0)),
                ('monthly_build_minutes', models.PositiveIntegerField(default=0)),
                ('max_studios', models.PositiveIntegerField(default=0)),
                ('max_reports', models.PositiveIntegerField(default=0)),
                ('max_memory_mb', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='orgs.organization')),
            ],
        ),
    ]
