# Generated by Django 5.2.17 on 2026-08-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_orgquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('verification_token', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='orgs.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain',), name='uniq_domain_claim')],
            },
        ),
    ]
