# Generated by Django 5.2.17 on 2026-08-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_orgdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
