# Generated by Django 5.2.17 on 2026-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_organization_onboarding_dismissed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgquota',
            name='max_storage_mb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
