# Generated by Django 5.2.17 on 2026-08-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_orgquota_max_storage_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_mfa', models.BooleanField(default=False, help_text='Every member who signs in with a password must have MFA enrolled.')),
                ('mfa_grace_days', models.PositiveIntegerField(default=7, help_text='Members without a device may still sign in for this many days after the policy turns on (or after their account is created), with a nag banner. 0 = enrollment required immediately.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='orgs.organization')),
            ],
        ),
    ]
