# Generated by Django 5.2.17 on 2026-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_orgsecuritypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_theme',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='lock_studio_theme',
            field=models.BooleanField(default=False),
        ),
    ]
