# Generated by Django 5.2.17 on 2026-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_organization_default_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=8),
        ),
    ]
