# Generated by Django 5.2.17 on 2026-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_org_default_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='retention_abandoned_upload_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='retention_built_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
