# Generated by Django 5.2.17 on 2026-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_orgassistantconfig_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgassistantconfig',
            name='price_in_per_mtok',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Input price in USD per million tokens. Required for models not in the built-in price list; overrides it otherwise.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orgassistantconfig',
            name='price_out_per_mtok',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Output price in USD per million tokens.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orgassistantconfig',
            name='share_report_source',
            field=models.BooleanField(default=True, help_text='Allow read_doc to send report source files (report.yaml, queries) to the model provider.'),
        ),
    ]
