# Generated by Django 5.2.17 on 2026-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_sso_generic_oidc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgssoconfig',
            name='extra_scopes',
            field=models.CharField(blank=True, default='', help_text='Scopes requested besides openid, profile and email, space-separated. Only for providers that emit the groups claim on request (see the SSO docs).', max_length=200),
        ),
    ]
