# LDAP / Active Directory as a second identity source on the same row
# (internal planning ticket #075): auth_method picks OpenID Connect or a directory, and the
# directory fields sit beside the OIDC ones. Routing, group mapping,
# provisioning and enforcement are shared, so nothing else moves.
# Generated by Django 5.2.17 on 2026-09-07 21:33

import apps.core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_orgssoconfig_extra_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgssoconfig',
            name='auth_method',
            field=models.CharField(choices=[('oidc', 'OpenID Connect'), ('ldap', 'LDAP / Active Directory')], default='oidc', max_length=8),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_bind_dn',
            field=models.CharField(blank=True, default='', help_text='Service account that searches for users; blank binds anonymously.', max_length=300),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_bind_password',
            field=apps.core.crypto.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_ca_cert',
            field=models.TextField(blank=True, default='', help_text="PEM certificate(s) of the CA that signed the directory's certificate, for a private CA."),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_email_attr',
            field=models.CharField(default='mail', max_length=100),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_group_attr',
            field=models.CharField(default='memberOf', help_text="Attribute listing the user's group DNs; the group mapping keys on those DNs.", max_length=100),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_name_attr',
            field=models.CharField(default='displayName', max_length=100),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_server_uri',
            field=models.CharField(blank=True, default='', help_text='ldap://host:389 (upgraded with StartTLS) or ldaps://host:636.', max_length=300),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_user_filter',
            field=models.CharField(default='(|(mail={login})(userPrincipalName={login}))', help_text='{login} is the email typed at the login form (escaped).', max_length=500),
        ),
        migrations.AddField(
            model_name='orgssoconfig',
            name='ldap_user_search_base',
            field=models.CharField(blank=True, default='', help_text='e.g. ou=people,dc=corp,dc=example.', max_length=300),
        ),
    ]
