# Generated by Django 5.2.17 on 2026-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_sso_ldap'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='api_keys_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
