# Generated by Django 5.2.17 on 2026-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_organization_api_keys_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgassistantconfig',
            name='actions_enabled',
            field=models.BooleanField(default=False, help_text='Let the assistant propose portal actions: configure or test a data source, build a report, publish repository changes. Nothing runs until the user approves the proposal in the panel.'),
        ),
    ]
