# Generated by Django 5.2.17 on 2026-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_merge_report_access_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='price_in_per_mtok',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD per million tokens. Optional with both budgets blank; required for unlisted models when either budget is set. Overrides built-in rates.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='price_out_per_mtok',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD per million tokens. Set both prices or leave both blank.', max_digits=10, null=True),
        ),
    ]
