# Generated by Django 5.2.17 on 2026-10-10 05:06

import apps.core.crypto
from django.db import migrations, models


def migrate_legacy_connections(apps, schema_editor):
    Config = apps.get_model("orgs", "OrgAssistantConfig")
    for cfg in Config.objects.exclude(base_url="").iterator():
        # Preserve the endpoint, dialect and model for existing keyless gateways.
        if not cfg.api_key:
            cfg.auth_mode = "none"
        cfg.save(update_fields=["auth_mode"])


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_assistant_model_pricing_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgassistantconfig',
            name='auth_mode',
            field=models.CharField(choices=[('api_key', 'API key'), ('none', 'No authentication (gateway handles it)'), ('access_key', 'AWS access key'), ('client_secret', 'Microsoft Entra client secret'), ('service_account', 'Google service account'), ('workload', 'Operator-authorized workload identity')], default='api_key', max_length=32),
        ),
        migrations.AddField(
            model_name='orgassistantconfig',
            name='cloud_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgassistantconfig',
            name='cloud_credentials',
            field=apps.core.crypto.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgassistantconfig',
            name='config_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orgassistantconfig',
            name='connection_check',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='base_url',
            field=models.URLField(blank=True, help_text='Optional provider endpoint or compatible gateway URL.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='model',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('litellm', 'LiteLLM'), ('openrouter', 'OpenRouter'), ('deepseek', 'DeepSeek'), ('azure', 'Azure OpenAI'), ('bedrock', 'Amazon Bedrock'), ('vertex', 'Vertex AI'), ('custom', 'Custom OpenAI-compatible endpoint')], default='anthropic', max_length=32),
        ),
        migrations.RunPython(migrate_legacy_connections, migrations.RunPython.noop),
    ]
