# Generated by Django 5.2.17 on 2026-10-10 14:50

import apps.core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_orgassistantconfig_auth_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='auth_mode',
            field=models.CharField(choices=[('api_key', 'API key'), ('none', 'No authentication (gateway handles it)'), ('access_key', 'AWS access key'), ('client_secret', 'Microsoft Entra client secret'), ('service_account', 'Google service account'), ('workload', 'Operator-authorized workload identity')], default='api_key', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='cloud_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='cloud_credentials',
            field=apps.core.crypto.EncryptedJSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='config_revision',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orgassistantconfig',
            name='connection_check',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
