"""Scaffolding tool for creating new reports.

Usage:
    python -m trellum.new my_report_name
    python -m trellum.new revenue-trends --studio my-studio --category Revenue
"""

from __future__ import annotations

import argparse
import os


def _project_root() -> str:
    from trellum.project import get_project_root
    return get_project_root()


def _sibling_examples(root: str, exclude_slug: str) -> list[tuple[str, str]]:
    """``(slug, comma-joined tags)`` for every buildable report in the project.

    Read live from ``reports/*/report.yaml`` at scaffold time, never from a
    kept list -- a kept list is how this codebase has produced fabricated
    report names twice before. A report with no tags is still listed: it
    exists, and "no tags" is more honest than pretending it does not.

    Sorted by tag count, most first, so the fullest worked example leads and a
    reader who stops at the first line stops at the best one.
    """
    import yaml

    out: list[tuple[str, str]] = []
    reports_dir = os.path.join(root, "reports")
    try:
        entries = sorted(os.listdir(reports_dir))
    except OSError:
        return []
    for entry in entries:
        if entry == exclude_slug or entry.startswith(("_", ".")):
            continue
        yaml_path = os.path.join(reports_dir, entry, "report.yaml")
        try:
            with open(yaml_path, encoding="utf-8") as f:
                cfg = yaml.safe_load(f) or {}
        except (OSError, yaml.YAMLError):
            continue
        tags = cfg.get("tags") or []
        if not isinstance(tags, list):
            tags = []
        out.append((entry, ", ".join(str(t) for t in tags)))
    out.sort(key=lambda pair: pair[1].count(",") + bool(pair[1]), reverse=True)
    return out


REPORT_YAML_TEMPLATE = """# ─── Identity ───────────────────────────────────────────────
name: "{name}"
slug: {slug}
description: "TODO: describe this report"
version: 0.1.0

# ─── Scheduling ─────────────────────────────────────────────
schedule:
  cron: "0 * * * *"       # Every hour -- adjust as needed
  timezone: UTC

# ─── Classification ─────────────────────────────────────────
tags:
  - TODO
studio: {studio}
category: {category}

# ─── Data Sources ────────────────────────────────────────────
data_sources:
{source_block}

# ─── Annotations ─────────────────────────────────────────────
# annotations: true   # Set false to disable events.yaml chart annotations
#                      # Requires events.yaml at project root (python -m trellum.init)

# ─── Display ─────────────────────────────────────────
display:
  icon: file-text
  color: "#4e79a7"
  priority: 99
"""

GENERATOR_TEMPLATE = '''"""
{name} report generator.

Generated by: python -m trellum.new {slug}
"""

from datetime import timedelta

from trellum import BaseReport
from trellum.components import (
    DataSource, FilterBar, LineChart, BarChart, KpiRow,
)
from trellum.data import query_df
from . import queries

_LOOKBACK_DAYS = 90


class {class_name}(BaseReport):

    def generate(self, ctx):
        conn = ctx.get_connection("{source}")

        # A lookback window rather than "the last few days": if the warehouse
        # is not current, a recent window returns zero rows, and the report
        # then builds clean and empty rather than failing. `python -m trellum
        # data` prints each table's date span. Widen _LOOKBACK_DAYS to cover it.
        start = (ctx._now_utc - timedelta(days=_LOOKBACK_DAYS)).strftime("%Y-%m-%d")
        df = query_df(conn, queries.SAMPLE, params={{
            "start_date": start,
            "end_date": ctx.today,
        }})

        ctx.add_section("", [
            DataSource("main", df),
            FilterBar("main", df, filters=[
                {{"column": "event_date", "label": "Date Range",
                 "type": "date_range"}},
                {{"column": "category", "label": "Category"}},
            ]),
        ])

        ctx.add_section("Overview", [
            KpiRow([
                {{"label": "Sample Metric", "value": 42, "format": "number"}},
            ], dataset_id="main"),
            LineChart(df, x="event_date", y="total",
                      title="Daily Trend", dataset_id="main"),
        ])

        # No trailing "Detail" table of raw rows. That habit spread from this
        # very template into every report built from it, and owners deleted it
        # every time: a row dump answers no question the page asked. Use
        # DataTable when a table IS the answer (a ranked decision table), not
        # as an appendix.
'''

QUERIES_TEMPLATE = '''"""SQL queries for {name}.

Organize all queries as module-level constants.
Use :param_name for date placeholders.
"""

SAMPLE = """
SELECT event_date,
       category,
       SUM(value) AS total
FROM some_table
WHERE event_date BETWEEN :start_date AND :end_date
GROUP BY 1, 2
ORDER BY 1
"""
'''


def slugify(name: str) -> str:
    return name.lower().replace(" ", "-").replace("_", "-")


def to_class_name(slug: str) -> str:
    return "".join(word.capitalize() for word in slug.replace("-", "_").split("_")) + "Report"


def _scaffold_source(studio: str, studio_upper: str) -> tuple[str, str]:
    """Which data source the scaffold should point at.

    It used to invent ``vertica_{studio}`` unconditionally. In any project that
    is not a Vertica shop -- including the demo warehouse the framework ships --
    the first build then fails with::

        No data_source named 'vertica_default' in report.yaml or
        data-sources/config.yaml. Available: ['demo_db']

    Two measured runs hit that, and each had to work out the real name and edit
    two files before anything could run. The project already declares its
    sources in ``data-sources/config.yaml``; use them.

    Only when exactly one is configured, because picking for the author out of
    several is a guess they would have to check anyway. With none configured
    (a greenfield project) the Vertica block stays as a worked placeholder.
    """
    try:
        from trellum.data.datasource_config import load_datasource_config
        sources = load_datasource_config()
    except Exception:
        sources = {}

    if len(sources) == 1:
        only = next(iter(sources))
        return only, f"  - {only}"

    if sources:
        listed = "\n".join(f"  #   {n}" for n in sources)
        return next(iter(sources)), (
            f"  # This project configures several sources -- pick one:\n"
            f"{listed}\n"
            f"  - {next(iter(sources))}"
        )

    return f"vertica_{studio}", (
        f"  - name: vertica_{studio}\n"
        f"    type: vertica\n"
        f"    secret: bi-reports/{studio}/vertica\n"
        f"    local_env: BI_VERTICA_{studio_upper}"
    )


def create_report(
    name: str,
    studio: str = "default",
    category: str = "Uncategorized",
):
    slug = slugify(name)
    class_name = to_class_name(slug)
    studio_upper = studio.upper()
    human_name = name.replace("-", " ").replace("_", " ").title()

    root = _project_root()
    report_dir = os.path.join(root, "reports", slug)
    # Collected before the scaffold exists so the new, empty report can never
    # list itself as an example of anything.
    _examples_snapshot = _sibling_examples(root, slug)

    if os.path.exists(report_dir):
        print(f"Report directory already exists: {report_dir}")
        return

    os.makedirs(report_dir, exist_ok=True)

    source, source_block = _scaffold_source(studio, studio_upper)

    yaml_content = REPORT_YAML_TEMPLATE.format(
        name=human_name, slug=slug, studio=studio,
        category=category, studio_upper=studio_upper,
        source_block=source_block,
    )
    gen_content = GENERATOR_TEMPLATE.format(
        name=human_name, slug=slug, studio=studio,
        class_name=class_name, source=source,
    )
    queries_content = QUERIES_TEMPLATE.format(name=human_name)

    with open(os.path.join(report_dir, "__init__.py"), "w", encoding="utf-8") as f:
        pass
    with open(os.path.join(report_dir, "report.yaml"), "w", encoding="utf-8") as f:
        f.write(yaml_content)
    with open(os.path.join(report_dir, "generator.py"), "w", encoding="utf-8") as f:
        f.write(gen_content)
    with open(os.path.join(report_dir, "queries.py"), "w", encoding="utf-8") as f:
        f.write(queries_content)

    # The templates below contain box-drawing characters, and a default Windows
    # console cannot encode them -- printing one aborts with UnicodeEncodeError
    # after the files are already on disk, so the scaffold "fails" having
    # succeeded. Third entry point to need this; runner.py has had it for ages.
    try:
        from trellum.runner import _force_utf8_console
        _force_utf8_console()
    except Exception:
        pass

    print(f"Created report: {report_dir}")
    print("  report.yaml  -- edit name, description, schedule, tags")
    print("  generator.py -- implement generate() with your data logic")
    print("  queries.py   -- add SQL queries")

    # These three were printed in full for a while, on the theory that the
    # caller would then not have to go and read them. Measured: it read all
    # three back anyway, with the contents already on screen. Reading a file
    # natively costs an agent almost nothing, so there was never much to save --
    # and printing ~1,200 tokens into every scaffold to save nothing is the
    # wrong side of the trade.
    print(f"\n{'-' * 66}")
    print("Edit those three, then build. `--no-serve` exits when done; without")
    print("it the command starts a preview server and does not return:")
    print(f"  python -m trellum.run reports/{slug} --no-serve")
    print("")
    print("Columns come from your warehouse, not from the template above:")
    print("  python -m trellum data")

    # Which existing report to read as a worked example. Measured on the
    # benchmark task: agents spend the largest pre-build bucket surveying
    # reports/ for one whose shape matches theirs -- two globs and five file
    # reads in the last run -- because nothing says what any of them
    # demonstrates. The tags in each report.yaml already say. Listing them is
    # derived, so it cannot go stale, and it turns the survey into "read the
    # one whose tags match".
    examples = _examples_snapshot
    if examples:
        print("")
        print("Worked examples already in reports/ -- pick the one whose tags")
        print("match your task and read its three files before writing yours:")
        for ex_slug, tags in examples:
            print(f"  {ex_slug:<22} {tags}")

    events_path = os.path.join(root, "events.yaml")
    if not os.path.exists(events_path):
        print("")
        print("Hint: Create events.yaml at the project root to enable chart annotations.")
        print("      Run: python -m trellum.init")


def main():
    parser = argparse.ArgumentParser(description="Create a new BI report")
    parser.add_argument("name", help="Report name or slug (e.g. daily-revenue)")
    parser.add_argument("--studio", default="default", help="Studio/tenant identifier — whatever grouping your project uses (default: 'default')")
    parser.add_argument("--category", default="Uncategorized", help="Category used to group reports (default: Uncategorized)")
    args = parser.parse_args()

    create_report(args.name, args.studio, args.category)


if __name__ == "__main__":
    main()
